# 2GB ram minimum for kubernetes
default_flavor: c1.c1r2
docker_lib: docker-ce=17.03.2~ce-0~ubuntu-xenial
kubeadm_extra_args: "--pod-network-cidr=192.168.0.0/16 --apiserver-cert-extra-sans '{{ ansible_host  }}'"
flannel_version: v0.9.1
calico_network_configs:
  - https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
  - https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
main_security_groups:
  - group: "manage{{ suffix }}" 
    port: 22 
    remote_ip_prefix: "{{ ssh_remote_cidr }}"


security_groups: "{{ main_security_groups + host_security_groups }}"
