- name: Install docker
  hosts: localhost
  become: yes
  roles:
    - docker
    - docker-compose
  pre_tasks: 

    - name: Bail out if not an ubuntu distribution
      when: ansible_distribution != "Ubuntu"
      fail:
        msg: "Sorry this only works on Ubuntu"

    - name: Apt dist upgrade
      apt:
        upgrade: dist
        autoremove: yes

    - name: Make sure old versions of docker are not installed
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-engine
        - docker-io

